# Codecov configuration for JMESPath documentation site
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...95"

  status:
    project:
      default:
        target: 75%
        threshold: 2%
        base: auto
        flags:
          - unittests
        paths:
          - "src/"
          - "scripts/"
    
    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto
        flags:
          - unittests

  ignore:
    - "tests/"
    - "node_modules/"
    - "dist/"
    - "docs/"
    - "build/"
    - "coverage/"
    - "*.config.js"
    - "*.config.ts"
    - ".github/"

flags:
  unittests:
    paths:
      - src/
      - scripts/
    carryforward: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true
