name: Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: Spec repo version tag
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: build/
    - uses: actions/checkout@v3
      with:
        repository: https://github.com/jmespath-community/jmespath.spec.git
        ref: ${{ github.event.inputs.version }}
        path: content/spec
    - uses: actions/checkout@v3
      with:
        repository: https://github.com/jmespath-community/jmespath.spec.wiki.git
        path: content/wiki
    - name: Install ncat
      run: 'sudo apt-get -y install ncat'
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    - name: Dump tag message
      run: "git -C content/spec tag -l --format='%(contents)' ${{ github.event.inputs.version }} > TAG_MESSAGE"
    - name: Build
      env:
        OUTPUTDIR: "build/${{ github.event.inputs.version }}"
      run: .github/workflows/build.sh
    - name: Update versions
      run: "git -C content/spec tag -l --format='%(refname:strip=2) %(authordate:short)' | sort -V > build/VERSIONS"
    - name: Update root
      run: "cp -f $(tail -1 VERSIONS | cut -d' ' -f1)/* ."
      working-directory: build/
    - name: Deploy
      if: github.ref == 'refs/heads/main'
      uses: EndBug/add-and-commit@v9.0.0
      with:
        cwd: build/
