name: 🧤 Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    ## checkout prerequisites

    - name: 📚 Checkout site
      uses: actions/checkout@v3

    - name: 📚 Checkout spec
      uses: actions/checkout@v3
      with:
        repository: jmespath-community/jmespath.spec.git
        ref: main
        path: spec

    - name: 📚 Checkout wiki
      uses: actions/checkout@v3
      with:
        repository: jmespath-community/jmespath.spec.wiki.git
        ref: master
        path: content/wiki

    ## install supporting software

    - name: 📘 Install ncat
      run: 'sudo apt-get -y install ncat'

    - name: 📘 Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    ## update home page

    - name: 📃 Checkout site gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: build/
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 📃 Generate site pages
      run:
        .github/workflows/gh-pages.sh "${{ github.ref_name }}"
      env:
        OUTPUTDIR: "build/${{ github.ref_name }}"

    ## publish home pages

    - name: ✉ Deploy
      if: github.ref == 'refs/heads/main'
      run: |
        git -C build/ config --local user.name Springcomp
        git -C build/ config --local user.email springcomp@users.noreply.github.com

        git -C build/ add .
        git -C build/ commit -m "Commit from GitHub Actions (Build)"
        git -C build/ push origin gh-pages --force
