name: Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: Spec repo version tag
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout site
      uses: actions/checkout@v3

    - name: Checkout site-ghpages
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: build/
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Checkout spec
      uses: actions/checkout@v3
      with:
        repository: jmespath-community/jmespath.spec.git
        ref: ${{ github.event.inputs.version }}
        path: spec

    - name: Checkout wiki
      uses: actions/checkout@v3
      with:
        repository: jmespath-community/jmespath.spec.wiki.git
        ref: master
        path: content/wiki

    - name: Install ncat
      run: 'sudo apt-get -y install ncat'

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Dump tag message
      run: "git -C spec tag -l --format='%(contents)' ${{ github.event.inputs.version }} > TAG_MESSAGE"

    - name: Build
      env:
        OUTPUTDIR: "build/${{ github.event.inputs.version }}"
      run: .github/workflows/build.sh

    - name: Update versions
      run: "cp build/VERSIONS VERSIONS.old; git -C spec tag -l --format='%(refname:strip=2) %(authordate:short)' | sort -V > build/VERSIONS"

    - name: Remove old versions
      run: "cut -d' ' -f1 VERSIONS ../VERSIONS.old | sort | uniq -u | xargs -l rm -rf"
      working-directory: build/

    - name: Update root
      run: "cp -fR $(cut -d' ' -f1 VERSIONS | grep -P '^v|^2015' | tail -1 )/* ."
      working-directory: build/

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      uses: EndBug/add-and-commit@v9.0.0
      with:
        cwd: build/
        push: origin gh-pages --force
