name: 🧤 Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    ## checkout prerequisites

    - name: 📚 Checkout site
      uses: actions/checkout@v3

    - name: 📚 Checkout spec
      uses: actions/checkout@v3
      with:
        repository: jmespath-community/jmespath.spec.git
        ref: main
        path: spec

    - name: 📚 Checkout wiki
      uses: actions/checkout@v3
      with:
        repository: jmespath-community/jmespath.spec.wiki.git
        ref: master
        path: content/wiki

    ## install supporting software

    - name: 📘 Install ncat
      run: 'sudo apt-get -y install ncat'

    - name: 📘 Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    ## update home page

    - name: 📃 Checkout site gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: build/
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 📃 Generate site pages
      run: |
        cd build/ && find . -maxdepth 1 -type f -exec git rm {} \; && cd ..

        git -C build/ rm -r wiki/
        git -C build/ checkout HEAD -- .nojekyll
        git -C build/ checkout HEAD -- CNAME
        git -C build/ checkout HEAD -- VERSIONS

        [ -e content/wiki/_Sidebar.md ] && rm content/wiki/_Sidebar.md

        .github/workflows/build.sh
      env:
        OUTPUTDIR: "build/${{ github.event.inputs.version }}"

    ## publish home pages

    - name: ✉ Deploy
      if: github.ref == 'refs/heads/main'
      uses: EndBug/add-and-commit@v9.0.0
      with:
        cwd: build/
        push: origin gh-pages --force
